# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FritzImageSegmentationDemo' do
  use_frameworks!

  pod 'Fritz', '~> 4.2.4'
  pod 'Fritz/VisionSegmentationModel/People/Fast'
end
