lane :dist do
  gym(
    workspace: 'Heartbeat.xcworkspace',
    scheme: 'Heartbeat',
    include_symbols: true,
    include_bitcode: true,
    export_xcargs: "-allowProvisioningUpdates"
  )

  deliver(
    team_id: 'T3RGJF7P9D',
    skip_metadata: true,
    skip_screenshots: true,
    force: true,
    edit_live: get_version_number(target: 'Heartbeat')
  )

  clean_build_artifacts
end
