# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FritzObjectDetectionDemo' do
  use_frameworks!

  pod 'Fritz', '~> 4.3.0-beta.1'
  pod 'Fritz/VisionObjectModel/Fast'

end
